model:
  name: "meta-llama/Llama-3.1-8B-Instruct"
  cache_dir: "models"

data:
  task_name: "ioi"
  tasks:
    ioi:
      prompt_types: ["ABBA", "BABA", "filler", "letter", "passive", "3-person"]
  n_data: 1000 # equal distribution of data for each prompt type. This is the total number of data for each prompt type, not 1000 for each prompt type.
  train_ratio: 0.6 # equal distribution of data for each prompt type
  val_ratio: 0.2
  test_ratio: 0.2
  only_correct: false

paths:
  output_dir: "data/dcd/ioi/llama-3.1-8b-instruct"

attribution:
  method: "EAP-IG-inputs"
  ablation: "patching"
  ig_steps: 5
  batch_size: 1
  level: "edge"
  max_examples: null

circuit_creation:
  baseline_methods: ["EAP"]
  random_seed: 42
