model:
  name: "Qwen/Qwen2.5-7B-Instruct"
  cache_dir: "models"

data:
  task_name: "sequence-completion"
  tasks:
    sequence-completion:
      prompt_types: ["2-gram-symbolic", "3-gram-symbolic", "4-gram-symbolic"]
  n_data: 1000 # equal distribution of data for each prompt type. This is the total number of data for each prompt type, not 1000 for each prompt type.
  train_ratio: 0.6
  val_ratio: 0.2
  test_ratio: 0.2
  only_correct: false

paths:
  output_dir: "data/dcd/sequence-completion/qwen2.5-7b-instruct"

attribution:
  method: "EAP-IG-inputs"
  ablation: "patching"
  ig_steps: 5
  batch_size: 1
  level: "edge"
  max_examples: null

circuit_creation:
  baseline_methods: ["EAP"]
  random_seed: 42
